name: Docker Image CI

on:
  push:
    branches: [ main, NAC_Create_Build_Images_Integration]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io/natecheadle

jobs:
  build-and-push-base-image:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        include:
        - os: "ubuntu-latest"
          image: "ubuntu-latest-llvm13.dockerfile"
        - os: "windows-latest"
          image: "windows-latest-llvm13.dockerfile"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{matrix.image}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{matrix.image}}